class Data:
    PHONE_VALID = "89111427949"
    MAIL_VALID = "volkovn94@gmail.com"
    MAIL_VALID_RANDOM = "kiki@gmail.com"
    MAIL_NO_VALID = "аофлафуауаш"
    PHONE_NO_VALID = "+711111111111"
    PASS_VALID = "Zx345678"
    PASS_NO_VALID = "grgrg"
    PASS_CYRILLIC = "приветпривет"
    PASS_NUMBERS = "1234567"
    CAPTCHA_NO_VALID = "ljnsfs"
    FIRST_NAME_VALID = "Никита"
    LAST_NAME_VALID = "Вилков"
    FIRST_NAME_1 = "Н"
    LAST_NAME_1 = "В"
    FIRST_NAME_2 = "Не"
    LAST_NAME_2 = "Ви"
    FIRST_NAME_30 = "Неавакпкекекпаевпанаркпапваыев"
    LAST_NAME_30 = "Викранвркнаомьаоврвпавовововов"
    FIRST_NAME_31 = "Неавакпкевкекпаевпанаркпапваыев"
    LAST_NAME_31 = "Викранвркнаомьаоварвпавовововов"

    REG_PASS_VALID = "Nb456789"
